apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nodejs-pvc

spec:

  storageClassName: ""

  volumeName: nodejs-pv

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
