apiVersion: v1
kind: Pod

metadata:
  name: app-logs-pod

spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: logs-storage
          mountPath: /var/log/nginx

  volumes:
    - name: logs-storage
      persistentVolumeClaim:
        claimName: app-logs-pvc
