apiVersion: v1
kind: Pod
metadata:
  name: pod1-cm

spec:

  containers:
    - name: cm-cont4
      image: nginx
      imagePullPolicy: IfNotPresent

      envFrom:
        - configMapRef:
            name: ivolve-cm
        -  secretRef:
            name: ivolve-secret
