apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodejs-app
  namespace: ivolve

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nodejs

  template:
    metadata:
      labels:
        app: nodejs

    spec:

      tolerations:
        - key: node
          operator: Equal
          value: worker
          effect: NoSchedule

      initContainers:
        - name: db-init
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nodejs-configmap

            - secretRef:
                name: nodejs-secret

          command:
            - sh
            - -c
            - |
              mysql -h "$DB_HOST" \
                    -u root \
                    -p"$MYSQL_ROOT_PASSWORD" \
                    -e "
                    CREATE DATABASE IF NOT EXISTS ivolve;
                    CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
                    GRANT ALL PRIVILEGES ON ivolve.* TO '$DB_USER'@'%';
                    FLUSH PRIVILEGES;
                    "

      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: nodejs-container
          image: ayatmoatamed/nodejs-app:v1

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: nodejs-configmap

            - secretRef:
                name: nodejs-secret

          volumeMounts:
            - name: storage
              mountPath: /app/data

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: nodejs-pvc
